[deps]
Asap = "763a8c06-ba23-41fc-b385-b3b57b52403a"
AsapOptim = "d81720e7-9d76-4c66-a69e-8f07ca321cc4"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
